# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        . venv/bin/activate
        pip install -r requirements.txt
        echo "{}" > config.json
    - name: Test
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER_PASSWD: ${{ secrets.DB_USER_PASSWD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python manage.py test
    - name: Deploy
      env:
        EB_ENV_NAME: "Flaskmovie-env"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: "ap-northeast-2"
        AWS_DEFAULT_OUTPUT: "json"
      run: |
        pip install awsebcli
        eb init --region ap-northeast-2 --platform docker
        eb deploy $EB_ENV_NAME
